"""M1 phase1 schema 14 tables

Revision ID: 10c107c08bc0
Revises: 20260619_m0_users
Create Date: 2026-06-19 10:12:08.057662+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic
revision: str = "10c107c08bc0"
down_revision: str | None = "20260619_m0_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("asset_kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("change_pct", sa.Float(), nullable=True),
        sa.Column("change_abs", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("turnover", sa.Float(), nullable=True),
        sa.Column("extra_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_asset_kind"), ["asset_kind"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_market_snapshots_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_snapshots_ts"), ["ts"], unique=False)

    op.create_table(
        "news_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("canonical_title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("news_count", sa.Integer(), nullable=False),
        sa.Column("top_source", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_events_last_seen_at"), ["last_seen_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_events_signature"), ["signature"], unique=False)

    op.create_table(
        "news_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("HIGHEST", "HIGH", "MEDIUM", "LOW", name="sourcepriority"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_pulled_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("news_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_news_sources_code"), ["code"], unique=True)

    op.create_table(
        "params",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PREMARKET", "MORNING", "NOON", "AFTERNOON", "CLOSE", "EVENING", name="reportkind"
            ),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("markdown", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("generated_by", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("push_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "kind", name="uq_report_date_kind"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_date"), ["date"], unique=False)
        batch_op.create_index(batch_op.f("ix_reports_kind"), ["kind"], unique=False)

    op.create_table(
        "sector_trends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("sector_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("change_pct", sa.Float(), nullable=True),
        sa.Column("news_heat", sa.Integer(), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("fund_status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("representative_stocks", sa.JSON(), nullable=False),
        sa.Column("trend_judgment", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sector_trends", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sector_trends_sector_name"), ["sector_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sector_trends_ts"), ["ts"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("target_kind", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("target_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_events_ts"), ["ts"], unique=False)

    op.create_table(
        "config_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_yaml", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_name", "version", name="uq_config_name_ver"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("source_msg_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["news_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["news_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_msg_id", name="uq_source_msgid"),
    )
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_items_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_items_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_news_items_published_at"), ["published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_items_source_id"), ["source_id"], unique=False)

    op.create_table(
        "param_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("change_reason", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("param_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_param_versions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_param_versions_key"), ["key"], unique=False)

    op.create_table(
        "push_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("ALERT_P0", "ALERT_P1", "ALERT_P2_BATCH", "REPORT", "MANUAL", name="pushkind"),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", "RATE_LIMITED", name="pushstatus"),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("push_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_push_records_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_push_records_sent_at"), ["sent_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_push_records_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_push_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "source_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column(
            "status", sa.Enum("OK", "DEGRADED", "DOWN", name="sourcehealthstatus"), nullable=False
        ),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("items_returned", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["news_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_health", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_health_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_source_health_ts"), ["ts"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "kind", "value", name="uq_user_kind_value"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "news_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column(
            "primary_category",
            sa.Enum(
                "MACRO_POLICY",
                "MARKET",
                "COMPANY_ANNOUNCEMENT",
                "OVERSEAS",
                "COMMODITY",
                "RISK_EVENT",
                "FUND_FLOW",
                "TRADE_HINT",
                name="newscategory",
            ),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("related_markets", sa.JSON(), nullable=False),
        sa.Column("related_sectors", sa.JSON(), nullable=False),
        sa.Column("related_symbols", sa.JSON(), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum(
                "STRONG_POSITIVE",
                "POSITIVE",
                "NEUTRAL",
                "NEGATIVE",
                "STRONG_NEGATIVE",
                "UNCERTAIN",
                name="sentiment",
            ),
            nullable=False,
        ),
        sa.Column("importance_score", sa.Integer(), nullable=False),
        sa.Column("urgency_score", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column(
            "impact_horizon",
            sa.Enum("IMMEDIATE", "INTRADAY", "SHORT_TERM", "MEDIUM_TERM", name="impacthorizon"),
            nullable=False,
        ),
        sa.Column(
            "action_hint",
            sa.Enum("WATCH", "FOLLOW", "ADD", "REDUCE", "AVOID", name="actionhint"),
            nullable=False,
        ),
        sa.Column("ai_reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("risk_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("processed_by", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["news_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("news_id", "processed_by", name="uq_news_processed_by"),
    )
    with op.batch_alter_table("news_analysis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_analysis_importance_score"), ["importance_score"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_news_analysis_news_id"), ["news_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_news_analysis_primary_category"), ["primary_category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_news_analysis_urgency_score"), ["urgency_score"], unique=False
        )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Enum("P0", "P1", "P2", "P3", name="alertlevel"), nullable=False),
        sa.Column("trigger_reason", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("pushed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["news_analysis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_news_id"), ["news_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_status"), ["status"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "timezone",
            existing_type=sa.VARCHAR(length=64),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "timezone",
            existing_type=sa.VARCHAR(length=64),
            server_default=sa.text("'Asia/Shanghai'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("'admin'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_news_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_level"))
        batch_op.drop_index(batch_op.f("ix_alerts_created_at"))

    op.drop_table("alerts")
    with op.batch_alter_table("news_analysis", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_analysis_urgency_score"))
        batch_op.drop_index(batch_op.f("ix_news_analysis_primary_category"))
        batch_op.drop_index(batch_op.f("ix_news_analysis_news_id"))
        batch_op.drop_index(batch_op.f("ix_news_analysis_importance_score"))

    op.drop_table("news_analysis")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_user_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("source_health", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_health_ts"))
        batch_op.drop_index(batch_op.f("ix_source_health_source_id"))

    op.drop_table("source_health")
    with op.batch_alter_table("push_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_push_records_user_id"))
        batch_op.drop_index(batch_op.f("ix_push_records_status"))
        batch_op.drop_index(batch_op.f("ix_push_records_sent_at"))
        batch_op.drop_index(batch_op.f("ix_push_records_kind"))

    op.drop_table("push_records")
    with op.batch_alter_table("param_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_param_versions_key"))
        batch_op.drop_index(batch_op.f("ix_param_versions_created_at"))

    op.drop_table("param_versions")
    with op.batch_alter_table("news_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_items_source_id"))
        batch_op.drop_index(batch_op.f("ix_news_items_published_at"))
        batch_op.drop_index(batch_op.f("ix_news_items_event_id"))
        batch_op.drop_index(batch_op.f("ix_news_items_content_hash"))

    op.drop_table("news_items")
    op.drop_table("config_versions")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    with op.batch_alter_table("sector_trends", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sector_trends_ts"))
        batch_op.drop_index(batch_op.f("ix_sector_trends_sector_name"))

    op.drop_table("sector_trends")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_kind"))
        batch_op.drop_index(batch_op.f("ix_reports_date"))

    op.drop_table("reports")
    op.drop_table("params")
    with op.batch_alter_table("news_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_sources_code"))

    op.drop_table("news_sources")
    with op.batch_alter_table("news_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_events_signature"))
        batch_op.drop_index(batch_op.f("ix_news_events_last_seen_at"))

    op.drop_table("news_events")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_ts"))
        batch_op.drop_index(batch_op.f("ix_market_snapshots_code"))
        batch_op.drop_index(batch_op.f("ix_market_snapshots_asset_kind"))

    op.drop_table("market_snapshots")
    # ### end Alembic commands ###
